### ISSUE TITLE
CanCan Authorizations

### ISSUE THREAD

**Issue by Xlaudius** [Xlaudius/tesis#19]
## Description
Code is missing from some views

## Impact
Running code after docker-compose in all ENV's results in an OK project on -p 3000, **BUT** the only 2 views working afther authentication as admin are HOME and PROPERTIES

@FelipeSepulvedaRozas  Could you handle this request please?

## Current Workaround

`load_and_authorize_resource` must be inserted on each controller for the view to load properly.

**Comment by RuxaiNezers** [comment]
fixed, add the line on all controllers
